<?php

/* Copyright (c) 2015 EVO Payments International - All Rights Reserved.
*
* This software and documentation is subject to and made
* available only pursuant to the terms of an executed license
* agreement, and may be used only in accordance with the terms
* of said agreement. This software may not, in whole or in part,
* be copied, photocopied, reproduced, translated, or reduced to
* any electronic medium or machine-readable form without
* prior consent, in writing, from EVO Payments International, INC.
*
* Use, duplication or disclosure by the U.S. Government is subject
* to restrictions set forth in an executed license agreement
* and in subparagraph (c)(1) of the Commercial Computer
* Software-Restricted Rights Clause at FAR 52.227-19; subparagraph
* (c)(1)(ii) of the Rights in Technical Data and Computer Software
* clause at DFARS 252.227-7013, subparagraph (d) of the Commercial
* Computer Software--Licensing clause at NASA FAR supplement
* 16-52.227-86; or their equivalent.
*
* Information in this software is subject to change without notice
* and does not represent a commitment on the part of EVO Payments International.
* 
* Sample Code is for reference Only and is intended to be used for educational purposes. It's the responsibility of 
* the software company to properly integrate into thier solution code that best meets thier production needs. 
*/

/**
 * EVO Snap* Hosted Form Block View.
 *
 * @category EVO
 * @package	Evo
 * @copyright Copyright (c) 2015 EVO Snap* (http://www.evosnap.com)
 * @license	EVO Payments International EULA
 */
?>
<?php $_code=$this->getMethodCode() ?>
<p style="vertical-align: middle;"><img class="credit-card-logo" src="<?php echo $this->getSkinUrl('images/evo/brand-logos.png')?>" alt="<?php echo $this->__('Credit Card Logos') ?>"  style="display: inline-block; margin: 5px; vertical-align: middle;" /><strong style="display: inline-block; vertical-align: middle;"><?php echo $this->__('Pay by VISA, MasterCard or Maestro') ?></strong></p>
<?php if($this->getMethod()->getConfigData('store_cards') && Mage::getSingleton('customer/session')->isLoggedIn()): ?>

    <?php
        $storedCards = $this->getStoredCards();
    ?>
    <div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <?php if($storedCards->getSize()): ?>
    
    <?php
        $cardCounter = 0;
        foreach ($storedCards as $storedCard) {
            $radioId = ''
    ?>
      <div>
        <input id="card<?php echo $cardCounter ?>" type="radio" name="payment[token_id]" value="<?php echo $storedCard->getData('id') ?>" <?php if($cardCounter == 0): ?> checked="checked" <?php endif; ?>/>
        <label for="card<?php echo $cardCounter ?>"><img src="<?php echo $this->getSkinUrl('images/evo/cc_'.strtolower($storedCard->getData('acct_type')).'.png') ?>" /><?php echo $this->htmlEscape($storedCard->getData('acct_name')) ?> / <?php echo $this->htmlEscape($storedCard->getPan()) ?> (<?php echo $storedCard->getExpirationDate() ?>)</label>
      </div>
    <?php
            $cardCounter++;
        }
    ?>
      <div>
        <input id="card<?php echo $cardCounter ?>" type="radio" name="payment[token_id]" value="-1" />
        <label for="card<?php echo $cardCounter ?>"><?php echo $this->__('Pay with a new card') ?></label>
        <input id="saveCreditCard" type="checkbox" name="payment[create_token]" value="true" />
        <label for="saveCreditCard"><?php echo $this->__('Store card data for future purchases.') ?> <a href="<?php echo $this->getMethod()->getConfigData('stored_cards_policy') ?>" style="margin-top: 0;"><?php echo $this->__('Privacy Policy') ?></a></label>
      </div>
    
    <?php else: ?>
      <div>
          <input id="saveCreditCard" type="checkbox" name="payment[create_token]" value="true" />
          <label for="saveCreditCard"><?php echo $this->__('Store card data for future purchases.') ?> <a href="<?php echo $this->getMethod()->getConfigData('stored_cards_policy') ?>" style="margin-top: 0;"><?php echo $this->__('Privacy Policy') ?></a></label>
      </div>
    <?php endif; ?>
    </div>
<?php endif; ?>