<?php

/* Copyright (c) 2016 EVO Payments International - All Rights Reserved.
*
* This software and documentation is subject to and made
* available only pursuant to the terms of an executed license
* agreement, and may be used only in accordance with the terms
* of said agreement. This software may not, in whole or in part,
* be copied, photocopied, reproduced, translated, or reduced to
* any electronic medium or machine-readable form without
* prior consent, in writing, from EVO Payments International, INC.
*
* Use, duplication or disclosure by the U.S. Government is subject
* to restrictions set forth in an executed license agreement
* and in subparagraph (c)(1) of the Commercial Computer
* Software-Restricted Rights Clause at FAR 52.227-19; subparagraph
* (c)(1)(ii) of the Rights in Technical Data and Computer Software
* clause at DFARS 252.227-7013, subparagraph (d) of the Commercial
* Computer Software--Licensing clause at NASA FAR supplement
* 16-52.227-86; or their equivalent.
*
* Information in this software is subject to change without notice
* and does not represent a commitment on the part of EVO Payments International.
* 
* Sample Code is for reference Only and is intended to be used for educational purposes. It's the responsibility of 
* the software company to properly integrate into thier solution code that best meets thier production needs. 
*/

/**
 * EVO Snap* Stored Cards View.
 *
 * @category EVO
 * @package	Evo
 * @copyright Copyright (c) 2016 EVO Snap* (http://www.evosnap.com)
 * @license	EVO Payments International EULA
 */
?>
<?php $_storedcards = $this->getStoredCards(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Stored Cards') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php echo $this->getPagerHtml(); ?>
<?php if($_storedcards->getSize()): ?>
<table class="data-table" id="my-cards-table">
    <col />
    <col />
    <col width="1">
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Name') ?></th>
            <th><?php echo $this->__('Card Number') ?></th>
            <th><?php echo $this->__('Exp. date') ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_storedcards as $_storedcard): ?>
        <tr>
            <td><?php echo $_storedcard->getAcctName() ?></td>
            <td><img class="ssc-credit-card-logo" src="<?php echo $this->getSkinUrl('images/evo/cc_'.strtolower($_storedcard->getAcctType()).'.png') ?>" style="display: inline-block; margin: 5px; vertical-align: middle;" />
            <?php echo $_storedcard->getPan() ?></td>
            <td><span class="nobr"><?php echo $_storedcard->getExpirationDate() ?></span></td>
            <td class="a-center">
                <span class="nobr">
                    <a href="#" onclick="return deleteStoredCard(<?php echo $_storedcard->getId() ?>);"><?php echo $this->__('Delete Card') ?></a>
                </span>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-cards-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have no stored cards.'); ?></p>
<?php endif ?>

<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>

<script type="text/javascript">
    function deleteStoredCard(storedCardId) {
        if(confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Are you sure you want to delete this stored card?')) ?>')) {
            window.location='<?php echo $this->getUrl("hostedpayments/index/delete") ?>id/'+storedCardId;
        }
        return false;
    }
</script>
